apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dev-app-config
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: dev-app-config
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/dev-app/config
        property: username
    - secretKey: password
      remoteRef:
        key: secret/dev-app/config
        property: password
