apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: dev
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: secret          
      version: v2
      auth:
        appRole:
          path: approle
          roleRef:                
            name: eso-vault-creds
            key: roleId
            namespace: dev
          secretRef:              
            name: eso-vault-creds
            key: secretId
            namespace: dev
